language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly-2018-06-18
      env:
        - CLIPPY_VERSION=0.0.208
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo fmt -- --check
        - cargo clippy -- -D clippy
