language: rust
cache: cargo
rust: stable
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
- cargo build --verbose
- cargo test --verbose
- cargo fmt -- --check
- cargo clippy --all-features -- -D clippy::all
