language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
before_script:
  - >
    [ "$TRAVIS_RUST_VERSION" != "nightly" ] || rustup component add rustfmt-preview
  - >
    [ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo install --force clippy || echo "clippy failed to install"
script:
  - >
    [ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo fmt -- --check
  - >
    [ "$TRAVIS_RUST_VERSION" != "nightly" ] || ! cargo clippy --version || cargo clippy -- -D clippy
  - cargo build --verbose
  - cargo test --verbose
matrix:
  fast_finish: true
