language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      env: CLIPPY
      install:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt -- --check
        - cargo clippy --all-features -- -D clippy
