[package]
name = "workspace"
version = "0.0.0"
authors = ["Matthias Totschnig <matthias@totschnig.org>","Roma Bhattacharjee <roma0615@gmail.com>"]

[dependencies]
clap = "2.31.2"

[[bin]]
name = "workspace"
path = "src/main.rs"
